# Generated by Django 5.1.4 on 2024-12-14 18:56

import admission_enquiry.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Counsellor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('assigned_students', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='AdmissionEnquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('parent_name', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=15)),
                ('course_preferred_1', models.CharField(max_length=50)),
                ('course_preferred_2', models.CharField(blank=True, max_length=50, null=True)),
                ('course_preferred_3', models.CharField(blank=True, max_length=50, null=True)),
                ('reference_source', models.CharField(max_length=50)),
                ('documents', models.FileField(blank=True, null=True, upload_to='documents/', validators=[admission_enquiry.models.validate_file_extension])),
                ('assigned_counsellor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='admission_enquiry.counsellor')),
            ],
        ),
    ]
