# Generated by Django 5.1.4 on 2024-12-17 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admission_enquiry', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='counsellor',
            name='name',
            field=models.CharField(default='Default Name', max_length=100, unique=True),
        ),
    ]
