# Generated by Django 5.1.4 on 2024-12-17 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admission_enquiry', '0003_counsellor_email_alter_counsellor_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='counsellor',
            name='email',
            field=models.EmailField(default='default@example.com', max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='counsellor',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
