# Generated by Django 5.1.4 on 2024-12-18 13:23

import admission_enquiry.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admission_enquiry', '0004_alter_counsellor_email_alter_counsellor_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdmissionForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('parent_name', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=15)),
                ('last_qualification', models.CharField(max_length=100)),
                ('aadhar_number', models.CharField(max_length=12)),
                ('documents', models.FileField(upload_to='supporting_documents/', validators=[admission_enquiry.models.validate_file_extension])),
            ],
        ),
        migrations.AlterField(
            model_name='counsellor',
            name='email',
            field=models.EmailField(max_length=254, null=True, unique=True),
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_mode', models.CharField(choices=[('Online', 'Online'), ('Offline', 'Offline')], max_length=50)),
                ('transaction_id', models.CharField(blank=True, max_length=50, null=True)),
                ('date', models.DateField()),
                ('payee_name', models.CharField(max_length=100)),
                ('admission_form', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='admission_enquiry.admissionform')),
            ],
        ),
    ]
