# Generated by Django 5.1.4 on 2024-12-18 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admission_enquiry', '0005_admissionform_alter_counsellor_email_payment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='admissionenquiry',
            name='documents',
        ),
    ]
