# Generated by Django 5.1.1 on 2025-02-02 07:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admission_enquiry', '0006_remove_admissionenquiry_documents'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='admissionenquiry',
            name='assigned_counsellor',
        ),
    ]
