# Generated by Django 5.1.1 on 2025-02-05 19:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admission_enquiry', '0007_remove_admissionenquiry_assigned_counsellor'),
    ]

    operations = [
        migrations.AddField(
            model_name='admissionenquiry',
            name='assigned_counsellor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='admission_enquiry.counsellor'),
        ),
        migrations.AddField(
            model_name='admissionenquiry',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default='NIL'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='payment',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
