# Generated by Django 5.1.1 on 2025-02-08 06:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admission_enquiry', '0008_admissionenquiry_assigned_counsellor_and_more'),
    ]

    operations = [
    ]
